parameters:
    dream_store.seller.form.type.stock.class: DreamStore\SellerBundle\Form\StockType
    dream_store.seller.form.type.price.class: DreamStore\SellerBundle\Form\PriceType

services:
    dream_store.seller.form.type.stock:
        class: DreamStore\SellerBundle\Form\StockType
        arguments: [ @service_container ]
        tags:
              - { name: form.type, alias: dreamstore_sellerbundle_stocktype }

    dream_store.seller.form.type.price:
        class: DreamStore\SellerBundle\Form\PriceType
        arguments: [ @service_container ]
        tags:
              - { name: form.type, alias: dreamstore_sellerbundle_pricetype }