parameters:
#    dream_store_seller.example.class: DreamStore\SellerBundle\Example

services:
#    dream_store_seller.example:
#        class: %dream_store_seller.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
