dream_store_payment:
    resource: "@DreamStorePaymentBundle/Resources/config/routing.yml"
    prefix:   /payment

dream_store_customer:
    resource: "@DreamStoreCustomerBundle/Resources/config/routing.yml"
    prefix:   /

dream_store_seller:
    resource: "@DreamStoreSellerBundle/Resources/config/routing.yml"
    prefix:   /seller

payum_capture:
    resource: "@PayumBundle/Resources/config/routing/capture.xml"

payum_authorize:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

payum_notify:
    resource: "@PayumBundle/Resources/config/routing/notify.xml"

#hwi_oauth_redirect:
#    resource: "@HWIOAuthBundle/Resources/config/routing/redirect.xml"
#    prefix:   /connect

#hwi_oauth_login:
#    resource: "@HWIOAuthBundle/Resources/config/routing/login.xml"
#    prefix:   /login

#google_login:
#    pattern: /login/check-google
