security:
    encoders:
        Symfony\Component\Security\Core\User\User: plaintext

    role_hierarchy:
        ROLE_ADMIN:       ROLE_USER
        ROLE_SUPER_ADMIN: [ROLE_USER, ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH]

    providers:
        hwi:                               
            id: hwi_oauth.user.provider   
        in_memory:
            memory:
                users:
                    user:  { password: userpass, roles: [ 'ROLE_USER' ] }
                    admin: { password: adminpass, roles: [ 'ROLE_ADMIN' ] }

    firewalls:
        secured_area:
            oauth:
                resource_owners:
                    facebook:      /login_facebook
                    my_github:     /login/check-github
                    twitter:       /login/check-twitter
                login_path:        /login
                failure_path:      /login
                oauth_user_provider:
                    service: hwi_oauth.user.provider.entity

            # Turn on anonymous for testings need.
            anonymous: ~

    access_control:
        - { path: ^/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/show/, roles: ROLE_USER }
