dream_store_customer_homepage:
    path:     /
    defaults: { _controller: DreamStoreCustomerBundle:Home:index }

dream_store_customer_show:
    path:     /show/{id}
    defaults: { _controller: DreamStoreCustomerBundle:Home:show }

dream_store_customer_historical:
    path:     /historical
    defaults: { _controller: DreamStoreCustomerBundle:Home:historical }

dream_store_customer_deconnection:
    path:     /deconnection
    defaults: { _controller: DreamStoreCustomerBundle:Home:deconnection }
