parameters:
#    dream_store_payment.example.class: DreamStore\PaymentBundle\Example

services:
#    dream_store_payment.example:
#        class: %dream_store_payment.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
